CREATE TABLE IF NOT EXISTS public.product (
	product_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	product_name varchar(64) NOT NULL,
	product_code varchar(10) NOT NULL,
	price varchar NOT NULL,
	description varchar(300) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.users (
	user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	login varchar(30) NOT NULL,
	inn char(12) NOT NULL,
	kpp char(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_params (
	id SERIAL PRIMARY KEY,
	quantity int NOT NULL,
	relevance bool NOT NULL,
	CONSTRAINT product_id FOREIGN KEY (id) REFERENCES public.product_params(id),
	CONSTRAINT user_id FOREIGN KEY (id) REFERENCES public.users(user_id)
);

INSERT INTO product (product_id ,product_code, price, product_name, description)
SELECT 1, '123-456', '11,11', 'test_product_1', 'description test'
WHERE
NOT EXISTS (
SELECT product_id FROM product WHERE product_id = 1
);

INSERT INTO product (product_id ,product_code, price, product_name, description)
SELECT 3, '345-456', '33,11', 'test_product_2', 'description test'
WHERE
NOT EXISTS (
SELECT product_id FROM product WHERE product_id = 3
);

INSERT INTO users (user_id, login, inn, kpp)
SELECT 1, 'test_user_1', '012345678910', '123456789'
WHERE
NOT EXISTS (
SELECT user_id FROM users WHERE user_id = 1
);

INSERT INTO users (user_id, login, inn, kpp)
SELECT 3, 'test_user_2', '012345678910', '123456789'
WHERE
NOT EXISTS (
SELECT user_id FROM users WHERE user_id = 3
);

DELETE FROM product WHERE product_id = 2;
DELETE FROM users WHERE user_id = 2;